name: Android CI (no-wrapper)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ANDROID_PLATFORM: "platforms;android-34"
  ANDROID_BUILD_TOOLS: "build-tools;34.0.0"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required Android packages
        run: |
          sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "${ANDROID_PLATFORM}" "${ANDROID_BUILD_TOOLS}" "platform-tools"
          yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses

      # 用 gradle-build-action 自带的 Gradle 8.7（不依赖 gradlew）
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
