name: Android CI (wrapper-ready)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ANDROID_PLATFORM: "platforms;android-34"
  ANDROID_BUILD_TOOLS: "build-tools;34.0.0"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required Android packages
        run: |
          sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "${ANDROID_PLATFORM}" "${ANDROID_BUILD_TOOLS}" "platform-tools"
          yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses

      # 如果 wrapper 的 jar 不在仓库里，这里会自动下载
      - name: Ensure Gradle Wrapper jar exists
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar missing, downloading..."
            mkdir -p gradle/wrapper
            curl -sLo gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-8.7-wrapper.jar
          fi

      - name: Fix line endings and make gradlew executable
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      # 官方推荐的新动作：仅做 Gradle 缓存和准备工作
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 用 wrapper 执行 Gradle（符合新规范，不再用老的 arguments 方式）
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
